chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.type === 'CAPTURE_PAGE') {
    capturePageState();
  } else if (message.type === 'EXECUTE_ACTION') {
    executeAction(message.action, message.params);
  }
});

async function capturePageState() {
  // Capture DOM snapshot
  const domSnapshot = document.documentElement.outerHTML;
  
  // Browser extensions need to use chrome.tabs.captureVisibleTab for screenshots
  // which is handled in the background script or sidepanel usually, 
  // but we can send the signal back.
  
  chrome.runtime.sendMessage({
    type: 'SEND_TO_CLI',
    payload: {
      type: 'PAGE_CAPTURE',
      url: window.location.href,
      dom: domSnapshot,
      // Screenshot will be added by background script
    }
  });
}

function executeAction(name, params) {
  console.log(`Executing action: ${name}`, params);
  // Implementation of action execution using selectors found in manifest
  // For now, logging. In a real scenario, this would use a mapping 
  // generated by the AI to click/type in the correct elements.
}
